/**
 * Router-specific Cloudflare Worker entry point for vinext App Router.
 *
 * New projects should usually use the router-selected entry in wrangler.jsonc:
 *   "main": "vinext/server/fetch-handler"
 *
 * This App Router entry remains available for existing configs and for custom
 * workers that need to opt into the App Router handler explicitly:
 *   "main": "vinext/server/app-router-entry"
 *
 * Or import and delegate to it from a custom worker:
 *   import handler from "vinext/server/app-router-entry";
 *   return handler.fetch(request, env, ctx);
 *
 * This file runs in the RSC environment. Configure the Cloudflare plugin with:
 *   cloudflare({ viteEnvironment: { name: "rsc", childEnvironments: ["ssr"] } })
 */

import "./server-globals.js";
// Virtual module generated by vinext at build time. The default export is
// the request handler; `__assetPrefix` and `__basePath` are named exports
// inlined from next.config (both as string literals) so this worker can
// recognise asset-shaped requests without invoking the handler. Types
// live in `virtual-vinext-rsc-entry.d.ts`; the generator is in
// `entries/app-rsc-entry.ts`.
import rscHandler, {
  __assetPrefix as __rscAssetPrefix,
  __basePath as __rscBasePath,
  __cacheabilityManifest as __rscCacheabilityManifest,
  __ensureInstrumentation,
  __ensureHybridPagesApplication,
  __imageAllowedWidths as __rscImageAllowedWidths,
  __imageConfig as __rscImageConfig,
  __prerenderSecret as __rscPrerenderSecret,
} from "virtual:vinext-rsc-entry";
import { runWithExecutionContext, type ExecutionContextLike } from "vinext/shims/request-context";
import { getCdnCacheAdapter } from "vinext/shims/cdn-cache";
// @ts-expect-error -- virtual module resolved by vinext at build time
import { registerConfiguredCacheAdapters } from "virtual:vinext-cache-adapters";
import { applyCdnResponseIdentityHeaders, validateCdnRequest } from "./cache-control.js";
// @ts-expect-error -- virtual module resolved by vinext at build time
import { registerConfiguredImageOptimizer } from "virtual:vinext-image-adapters";
import {
  getImageOptimizer,
  handleConfiguredImageOptimization,
  isImageOptimizationPath,
} from "./image-optimization.js";
import {
  createStaticAssetRequest,
  finalizeMissingStaticAssetResponse,
  resolveStaticAssetSignal,
} from "./worker-utils.js";
import {
  cloneRequestWithHeaders,
  filterInternalHeaders,
  isOpenRedirectShaped,
} from "./request-pipeline.js";
import {
  NEXT_ACTION_HEADER,
  RSC_ACTION_HEADER,
  RSC_HEADER,
  VINEXT_CACHEABILITY_PROBE_HEADER,
  VINEXT_CACHEABILITY_PROBE_QUERY_PARAM,
  VINEXT_PRERENDER_OBSERVATION_NONCE_HEADER,
  VINEXT_PRERENDER_ROUTE_PARAMS_HEADER,
  VINEXT_PRERENDER_SECRET_HEADER,
  VINEXT_REVALIDATE_HOST_HEADER,
} from "./headers.js";
import {
  readPrerenderObservationNonce,
  readTrustedPrerenderRouteParams,
  serializePrerenderRouteParamsHeader,
} from "./prerender-route-params.js";
import {
  badRequestResponse,
  notFoundResponse,
  notFoundStaticAssetResponse,
} from "./http-error-responses.js";
import { assetPrefixPathname, isNextStaticPath } from "../utils/asset-prefix.js";
import { createWorkerRevalidationContext } from "./worker-revalidation-context.js";
import {
  createWorkerPrerenderDiscoveryContext,
  createWorkerPrerenderReadinessResponse,
} from "./worker-prerender-discovery.js";
import { traceFrameworkRequest } from "./request-tracing.js";

// Precompute the path components used for `_next/static/*` 404 short-circuit
// detection. Both `__basePath` and `__assetPrefix` are inlined as
// compile-time constants in the generated RSC entry — see entries/app-rsc-entry.ts.
const __workerBasePath: string = typeof __rscBasePath === "string" ? __rscBasePath : "";
const __workerAssetPathPrefix: string = assetPrefixPathname(
  typeof __rscAssetPrefix === "string" ? __rscAssetPrefix : "",
);

type WorkerAssetEnv = {
  ASSETS?: {
    fetch(request: Request): Promise<Response> | Response;
  };
};

function isPotentialCompletedAdmissionRequest(request: Request): boolean {
  if (request.method !== "GET" && request.method !== "HEAD") return false;
  if (request.headers.has(NEXT_ACTION_HEADER) || request.headers.has(RSC_ACTION_HEADER))
    return false;
  return true;
}

export default {
  __ensureInstrumentation,
  async fetch(
    request: Request,
    env?: WorkerAssetEnv,
    ctx?: ExecutionContextLike,
  ): Promise<Response> {
    const handleFetch = async () => {
      await __ensureInstrumentation();
      const url = new URL(request.url);
      return traceFrameworkRequest({
        callback: async () =>
          applyCdnResponseIdentityHeaders(await handleRequest(request, env, ctx), request),
        getStatus: (response) => response?.status,
        headers: request.headers,
        isRsc: url.pathname.endsWith(".rsc") || request.headers.get(RSC_HEADER) === "1",
        method: request.method,
        target: url.pathname + url.search,
      });
    };
    return ctx ? runWithExecutionContext(ctx, handleFetch) : handleFetch();
  },
};

async function handleRequest(
  request: Request,
  env: WorkerAssetEnv | undefined,
  platformCtx: ExecutionContextLike | undefined,
): Promise<Response> {
  // The Node production server calls this Worker-style entry with a
  // server-owned loopback origin and must retain its HTTP revalidation path.
  // Cloudflare requests instead receive an in-process dispatcher so the
  // credential never leaves the Worker isolate.
  const requestCtx = platformCtx?.trustedRevalidateOrigin
    ? platformCtx
    : createWorkerRevalidationContext(platformCtx, (internalRequest, internalCtx) =>
        handleRequest(internalRequest, env, internalCtx),
      );
  // Registration must precede admission setup: the active adapter declares
  // whether a completed response is required before public cache headers.
  registerConfiguredCacheAdapters(env as Record<string, unknown> | undefined);
  const cdnCacheAdapter = getCdnCacheAdapter();
  let ctx = createWorkerPrerenderDiscoveryContext(requestCtx, request, __rscPrerenderSecret);
  const readinessResponse = createWorkerPrerenderReadinessResponse(ctx, request);
  if (readinessResponse) {
    if (readinessResponse.status === 204) await __ensureHybridPagesApplication();
    return (await validateCdnRequest(request)) ?? readinessResponse;
  }
  let finalizeCacheabilityResponse:
    | ((response: Response, ctx: ExecutionContextLike) => Promise<Response>)
    | undefined;
  if (request.headers.has(VINEXT_CACHEABILITY_PROBE_HEADER)) {
    // Keep the capture/classification runtime out of every ordinary request.
    // Authentication still happens before internal headers are removed below.
    const cacheability = await import("./cacheability-request.js");
    const probeContext = cacheability.createWorkerCacheabilityContext(
      ctx,
      request,
      __rscPrerenderSecret,
      cdnCacheAdapter.responseVary,
    );
    if (probeContext !== ctx) {
      ctx = probeContext;
      finalizeCacheabilityResponse = cacheability.finalizeWorkerCacheabilityResponse;
      // A staged version can propagate at different times for different edge
      // cache keys. The deploy client varies this reserved query value on each
      // retry, but application routing and dynamic API observation must see
      // the original request identity.
      const probeUrl = new URL(request.url);
      if (probeUrl.searchParams.has(VINEXT_CACHEABILITY_PROBE_QUERY_PARAM)) {
        probeUrl.searchParams.delete(VINEXT_CACHEABILITY_PROBE_QUERY_PARAM);
        request = new Request(probeUrl, request);
      }
    }
  }
  const requiresCompletedResponseAdmission =
    cdnCacheAdapter.requiresCompletedResponseAdmission === true;
  if (
    !finalizeCacheabilityResponse &&
    (__rscCacheabilityManifest || requiresCompletedResponseAdmission) &&
    isPotentialCompletedAdmissionRequest(request)
  ) {
    const cacheability = await import("./cacheability-request.js");
    const admissionContext = cacheability.createWorkerCacheabilityAdmissionContext(
      ctx,
      request,
      __rscCacheabilityManifest,
      process.env.__VINEXT_BUILD_ID,
      requiresCompletedResponseAdmission,
      cdnCacheAdapter.responseVary,
    );
    if (admissionContext !== ctx) {
      ctx = admissionContext;
      finalizeCacheabilityResponse = cacheability.finalizeWorkerCacheabilityResponse;
    }
  }

  // Register the image adapter before rendering can touch it. Cache adapters
  // were registered above because cacheability admission depends on them.
  registerConfiguredImageOptimizer(env as Record<string, unknown> | undefined);

  const cdnValidationResponse = await validateCdnRequest(request);
  if (cdnValidationResponse) return cdnValidationResponse;

  const url = new URL(request.url);

  if (isImageOptimizationPath(url.pathname) && env?.ASSETS && getImageOptimizer()) {
    const assetFetcher = env.ASSETS;
    return handleConfiguredImageOptimization(
      request,
      (assetPath) =>
        Promise.resolve(assetFetcher.fetch(new Request(new URL(assetPath, request.url)))),
      __rscImageAllowedWidths,
      __rscImageConfig,
    );
  }

  // Block protocol-relative URL open redirects (//evil.com/, /\evil.com/,
  // /%5Cevil.com/, /%2F/evil.com/). Check BEFORE decode so both literal and
  // percent-encoded variants are caught — encoded forms survive segment-wise
  // decoding and would otherwise reach trailing-slash redirect emitters.
  if (isOpenRedirectShaped(url.pathname)) {
    return notFoundResponse();
  }

  // Validate that percent-encoding is well-formed. The RSC handler performs
  // the actual decode + normalize; we only check here to return a clean 400
  // instead of letting a malformed sequence crash downstream.
  try {
    decodeURIComponent(url.pathname);
  } catch {
    // Malformed percent-encoding (e.g. /%E0%A4%A) — return 400 instead of throwing.
    return badRequestResponse();
  }

  // Valid assets are served by Cloudflare's ASSETS binding before the worker
  // is invoked. Missing asset-shaped requests still need to reach middleware
  // so it can rewrite or respond; a final 404 is converted back to Next.js's
  // canonical plain-text static-file response below.
  const missingBuildAsset = isNextStaticPath(
    url.pathname,
    __workerBasePath,
    __workerAssetPathPrefix,
  );

  // Strip internal headers from inbound requests before any handler or
  // middleware sees them. Must happen before the RSC handler runs.
  // Builds a new Headers — Request.headers is immutable in Workers.
  {
    // Only prod-server's `createNodeExecutionContext` sets `hostRuntime: "node"`,
    // and it runs after `nodeToWebRequest` verified the payload against the build
    // secret, so that payload is trusted and must survive filtering. A request
    // reaching a deployed Worker carries no such context, so a forged payload
    // stays dropped. Never trust a header for this decision.
    const trustedPrerenderRouteParams =
      ctx.hostRuntime === "node" ? readTrustedPrerenderRouteParams(request) : null;
    // Same for the observation nonce, which the App handler moves off the
    // request before middleware runs.
    const trustedPrerenderObservationNonce =
      ctx.hostRuntime === "node" && process.env.VINEXT_PRERENDER === "1"
        ? readPrerenderObservationNonce(request.headers)
        : null;
    const filteredHeaders = ctx.isInternalPagesRevalidation
      ? new Headers(request.headers)
      : filterInternalHeaders(request.headers);
    filteredHeaders.delete(VINEXT_PRERENDER_SECRET_HEADER);
    filteredHeaders.delete(VINEXT_REVALIDATE_HOST_HEADER);
    const prerenderRouteParamsHeader = serializePrerenderRouteParamsHeader(
      trustedPrerenderRouteParams,
    );
    if (prerenderRouteParamsHeader !== null) {
      filteredHeaders.set(VINEXT_PRERENDER_ROUTE_PARAMS_HEADER, prerenderRouteParamsHeader);
    }
    if (trustedPrerenderObservationNonce !== null) {
      filteredHeaders.set(
        VINEXT_PRERENDER_OBSERVATION_NONCE_HEADER,
        trustedPrerenderObservationNonce,
      );
    }
    request = cloneRequestWithHeaders(request, filteredHeaders);
  }

  // Do NOT decode/normalize the pathname here. The RSC handler
  // (virtual:vinext-rsc-entry) is the single point of decoding — it calls
  // decodeURIComponent + normalizePath on the incoming URL. Decoding here
  // AND in the handler would double-decode, causing inconsistent path
  // matching between middleware and routing.

  // Delegate to RSC handler (which decodes + normalizes the pathname itself),
  // wrapping in the ExecutionContext ALS scope so downstream code can reach
  // ctx.waitUntil() without having ctx threaded through every call site.
  const handleFn = () => rscHandler(request, ctx);
  const result = await (ctx ? runWithExecutionContext(ctx, handleFn) : handleFn());

  if (result instanceof Response) {
    let response = result;
    if (env?.ASSETS) {
      const assetFetcher = env.ASSETS;
      const assetResponse = await resolveStaticAssetSignal(response, {
        fetchAsset: (path) =>
          Promise.resolve(assetFetcher.fetch(createStaticAssetRequest(path, request))),
      });
      if (assetResponse) response = assetResponse;
    }
    response = finalizeMissingStaticAssetResponse(response, missingBuildAsset);
    return finalizeCacheabilityResponse ? finalizeCacheabilityResponse(response, ctx) : response;
  }

  if (result === null || result === undefined) {
    const response = missingBuildAsset ? notFoundStaticAssetResponse() : notFoundResponse();
    return finalizeCacheabilityResponse ? finalizeCacheabilityResponse(response, ctx) : response;
  }

  const response = new Response(String(result), { status: 200 });
  return finalizeCacheabilityResponse ? finalizeCacheabilityResponse(response, ctx) : response;
}
