/**
 * Internal HTTP header name constants used throughout vinext.
 *
 * Centralizes all custom header names so they are defined once and referenced
 * everywhere via imports. Keeping them in one module prevents typos, makes
 * rename-refactors trivial, and lets grep find every consumer instantly.
 *
 * Standard HTTP headers (Content-Type, Cache-Control, etc.) are intentionally
 * omitted — only vinext-internal and Next.js-protocol headers belong here.
 */

import {
  MIDDLEWARE_OVERRIDE_HEADERS,
  MIDDLEWARE_SET_COOKIE_HEADER,
  MIDDLEWARE_SKIP_HEADER,
  VINEXT_PRERENDER_ROUTE_PARAMS_HEADER,
  VINEXT_PRERENDER_SPECULATIVE_HEADER,
  VINEXT_REVALIDATE_HOST_HEADER,
} from "../utils/protocol-headers.js";

// ---------------------------------------------------------------------------
// Vinext-proprietary headers (`x-vinext-*` / `X-Vinext-*`)
// ---------------------------------------------------------------------------

/** ISR / page cache state indicator: "HIT" | "MISS" | "STALE" | "STATIC". */
export const VINEXT_CACHE_HEADER = "X-Vinext-Cache";

/** Next.js public ISR / page cache state indicator. */
export const NEXTJS_CACHE_HEADER = "x-nextjs-cache";

/** Next.js cache-tag metadata carried by prerendered App Router responses. */
export const NEXT_CACHE_TAGS_HEADER = "x-next-cache-tags";

/** Timing metrics: `handlerStart,compileMs,renderMs`. */
export const VINEXT_TIMING_HEADER = "x-vinext-timing";

/** Matched route returned from an independently hosted response stage. */
export const VINEXT_TRACE_ROUTE_HEADER = "X-Vinext-Trace-Route";

/** Exception metadata returned from an independently hosted response stage. */
export const VINEXT_TRACE_ERROR_HEADER = "X-Vinext-Trace-Error";

/** Fully buffered response metadata returned from an independently hosted response stage. */
export const VINEXT_TRACE_BUFFERED_BODY_HEADER = "X-Vinext-Trace-Buffered-Body";

/** Expected Worker version asserted by vinext staged warmup requests. */
export const VINEXT_EXPECTED_WORKER_VERSION_HEADER = "X-Vinext-Expected-Worker-Version";

/** Authenticated staged-Worker request asking for a completed App Page classification. */
export const VINEXT_CACHEABILITY_PROBE_HEADER = "X-Vinext-Cacheability-Probe";

/** Trusted route expected by an authenticated staged cacheability probe. */
export const VINEXT_CACHEABILITY_PROBE_ROUTE_HEADER = "X-Vinext-Cacheability-Probe-Route";

/**
 * Per-attempt cache buster used while a newly staged Worker version propagates.
 * Authenticated probe requests remove it before middleware or route code runs.
 */
export const VINEXT_CACHEABILITY_PROBE_QUERY_PARAM = "__vinext_cacheability_probe";

export {
  VINEXT_MW_CTX_HEADER,
  VINEXT_PRERENDER_ROUTE_PARAMS_HEADER,
  VINEXT_PRERENDER_SECRET_HEADER,
  VINEXT_PRERENDER_SPECULATIVE_HEADER,
  VINEXT_REVALIDATE_HOST_HEADER,
} from "../utils/protocol-headers.js";

/** Internal endpoint used to evaluate App Router generateStaticParams exports. */
export const VINEXT_PRERENDER_STATIC_PARAMS_PATH = "/__vinext/prerender/static-params";

/** Internal endpoint used to evaluate Pages Router getStaticPaths exports. */
export const VINEXT_PRERENDER_PAGES_STATIC_PATHS_PATH = "/__vinext/prerender/pages-static-paths";

/** Internal endpoint used to enumerate cached dynamic metadata route paths. */
export const VINEXT_PRERENDER_METADATA_ROUTES_PATH = "/__vinext/prerender/metadata-routes";

/** Internal endpoint used to verify staged Worker version routing without rendering a route. */
export const VINEXT_PRERENDER_READINESS_PATH = "/__vinext/prerender/readiness";

/** Response marker proving the staged Worker readiness short-circuit handled the request. */
export const VINEXT_PRERENDER_READINESS_HEADER = "X-Vinext-Prerender-Readiness";

/** TPR (Tailored Per-Request) revalidation interval in seconds. */
export const VINEXT_REVALIDATE_HEADER = "x-vinext-revalidate";

/** Actual Pages cache tag regenerated by an authenticated on-demand request. */
export const VINEXT_REVALIDATED_CACHE_TAG_HEADER = "x-vinext-revalidated-cache-tag";

/** Marker on cached ISR entries indicating RSC payload (value "1"). */
export const VINEXT_RSC_MARKER_HEADER = "x-vinext-rsc";

/** URL-encoded JSON route params carried on RSC responses. */
export const VINEXT_PARAMS_HEADER = "X-Vinext-Params";

/** Per-page dynamic stale time in seconds for App Router RSC responses. */
export const VINEXT_DYNAMIC_STALE_TIME_HEADER = "X-Vinext-Dynamic-Stale-Time";

/** Marks an RSC body carrying completion metadata after the Flight payload. */
export const VINEXT_RSC_COMPLETION_METADATA_HEADER = "X-Vinext-Rsc-Completion-Metadata";

/** URL-encoded rendered path and search after middleware/config rewrites. */
export const VINEXT_RENDERED_PATH_AND_SEARCH_HEADER = "X-Vinext-Rendered-Path-And-Search";

/** Prerender-only JSON side channel carrying request cacheLife metadata. */
export const VINEXT_PRERENDER_CACHE_LIFE_HEADER = "x-vinext-prerender-cache-life";

/**
 * Random per-request nonce the prerender sends with each App page request.
 * The prerender server frames the render observations it appends to the HTML
 * with it (see `server/prerender-render-observations.ts`).
 */
export const VINEXT_PRERENDER_OBSERVATION_NONCE_HEADER = "x-vinext-prerender-observation-nonce";

/** Marks a local prerender-server 500 that originated from a thrown render error. */
export const VINEXT_PRERENDER_RENDER_ERROR_HEADER = "x-vinext-prerender-render-error";

/** Internal marker persisted only inside metadata-route APP_ROUTE cache values. */
export const VINEXT_METADATA_ROUTE_CACHE_HEADER = "x-vinext-metadata-route-cache";

/** Disabled-by-default client hint describing already-held App Router payload entries. */
export const VINEXT_CLIENT_REUSE_MANIFEST_HEADER = "X-Vinext-Client-Reuse-Manifest";

/**
 * Side-channel signal that an RSC response (HTTP 200) encodes a `redirect()`
 * thrown during render. The header value is the redirect target (path-only
 * for same-origin, absolute for cross-origin). The flight body still carries
 * the canonical `NEXT_REDIRECT;...` digest so Next.js's own tests can read it
 * via response.body; this header is purely for vinext's own client
 * (`navigateRsc` in app-browser-entry.ts) to follow the redirect inside the
 * same navigation transaction — keeping `useTransition`'s pending state
 * continuous across the hop. Pre-1347 vinext relied on `fetch`'s auto-follow
 * of a 307 for that, but the new 200 + flight format leaves it without a
 * cheap way to detect the redirect ahead of stream decode.
 */
export const VINEXT_RSC_REDIRECT_HEADER = "X-Vinext-Rsc-Redirect";

/** History update mode encoded by a streamed RSC redirect. */
export const VINEXT_RSC_REDIRECT_TYPE_HEADER = "X-Vinext-Rsc-Redirect-Type";

// ---------------------------------------------------------------------------
// RSC protocol headers
// ---------------------------------------------------------------------------

/** Server Action invocation header (vinext/vite-rsc protocol). */
export const RSC_ACTION_HEADER = "x-rsc-action";

// ---------------------------------------------------------------------------
// Next.js compatibility headers
// ---------------------------------------------------------------------------

/** Next.js Server Action invocation header (fallback for x-rsc-action). */
export const NEXT_ACTION_HEADER = "next-action";

/** Next.js action-not-found indicator (value "1"). */
export const NEXTJS_ACTION_NOT_FOUND_HEADER = "x-nextjs-action-not-found";

/**
 * Seconds the client router may reuse this response, resolved from the
 * render's `cacheLife`. Mirrors Next.js's `NEXT_ROUTER_STALE_TIME_HEADER`;
 * kept out of `Cache-Control`, which owns the shared-cache dimensions.
 */
export const NEXT_ROUTER_STALE_TIME_HEADER = "x-nextjs-stale-time";

/**
 * Marks a streamed cacheable RSC response whose `cacheLife` claim had not
 * resolved at header time (value "1"). The client bounds such a response at
 * min(30s floor, dynamic bound) instead of its fallback TTL.
 */
export const VINEXT_STALE_TIME_PENDING_HEADER = "X-Vinext-Stale-Time-Pending";

/**
 * Deployment ID header used by the Pages Router for deployment-skew
 * protection. Set on every `/_next/data/` response so the client can detect
 * when a new deployment has been rolled out and trigger a hard navigation.
 * Mirrors `NEXT_NAV_DEPLOYMENT_ID_HEADER` from Next.js `lib/constants.ts`.
 */
export const NEXTJS_DEPLOYMENT_ID_HEADER = "x-nextjs-deployment-id";

/** Forwarded action marker — set when a request has already been forwarded between workers. */
export const ACTION_FORWARDED_HEADER = "x-action-forwarded";

// ---------------------------------------------------------------------------
// Server Action response headers (`x-action-*`)
// ---------------------------------------------------------------------------

/** Indicates revalidation occurred — value is JSON kind (1 = path/tag, 2 = dynamic-only). */
export const ACTION_REVALIDATED_HEADER = "x-action-revalidated";

/** Redirect URL from a Server Action. */
export const ACTION_REDIRECT_HEADER = "x-action-redirect";

/** Redirect type from a Server Action ("push" | "replace"). */
export const ACTION_REDIRECT_TYPE_HEADER = "x-action-redirect-type";

/** HTTP status for a Server Action redirect (e.g. "308"). */
export const ACTION_REDIRECT_STATUS_HEADER = "x-action-redirect-status";

// ---------------------------------------------------------------------------
// Middleware protocol headers (`x-middleware-*`)
// ---------------------------------------------------------------------------

export {
  MIDDLEWARE_HEADER_PREFIX,
  MIDDLEWARE_SET_COOKIE_HEADER,
  MIDDLEWARE_SKIP_HEADER,
} from "../utils/protocol-headers.js";

/** Signal from `NextResponse.next()` — value "1" means "continue to next handler". */
export const MIDDLEWARE_NEXT_HEADER = "x-middleware-next";

/** Rewrite destination URL set by `NextResponse.rewrite()`. */
export const MIDDLEWARE_REWRITE_HEADER = "x-middleware-rewrite";

/** Redirect URL set by middleware. */
const MIDDLEWARE_REDIRECT_HEADER = "x-middleware-redirect";

// ---------------------------------------------------------------------------
// Next.js / RSC flight headers (forwarded through middleware)
// ---------------------------------------------------------------------------

export {
  NEXT_ROUTER_PREFETCH_HEADER,
  NEXT_ROUTER_SEGMENT_PREFETCH_HEADER,
  NEXT_ROUTER_STATE_TREE_HEADER,
  NEXT_URL_HEADER,
  RSC_HEADER,
  VINEXT_INTERCEPTION_CONTEXT_HEADER,
  VINEXT_INTERCEPTION_ID_HEADER,
  VINEXT_MOUNTED_SLOTS_HEADER,
  VINEXT_RSC_RENDER_MODE_HEADER,
  VINEXT_RSC_STATE_FINGERPRINT_HEADER,
  VINEXT_RSC_VARY_HEADER,
  isVinextRscVaryField,
} from "./app-rsc-vary.js";

export const NEXT_REQUEST_ID_HEADER = "x-nextjs-request-id";
export const NEXT_HTML_REQUEST_ID_HEADER = "x-nextjs-html-request-id";

/** Lowercase flight header variants used in middleware forwarding. */
export const FLIGHT_HEADERS: readonly string[] = [
  "rsc",
  "next-router-state-tree",
  "next-router-prefetch",
  "next-hmr-refresh",
  "next-router-segment-prefetch",
  "x-vinext-rsc-state-fingerprint",
];

// ---------------------------------------------------------------------------
// Vercel / Now.sh legacy internal headers (stripped from inbound requests)
// ---------------------------------------------------------------------------

const NOW_ROUTE_MATCHES_HEADER = "x-now-route-matches";
const MATCHED_PATH_HEADER = "x-matched-path";
const NEXTJS_DATA_HEADER = "x-nextjs-data";
const NEXT_RESUME_STATE_LENGTH_HEADER = "x-next-resume-state-length";

// ---------------------------------------------------------------------------
// Internal headers blocklist — stripped from inbound requests for security
// ---------------------------------------------------------------------------

/**
 * Headers that must be stripped from external requests before any handler
 * processes them. An attacker could forge these to influence routing or
 * impersonate internal data fetches.
 *
 * Ported from Next.js `INTERNAL_HEADERS`:
 * https://github.com/vercel/next.js/blob/canary/packages/next/src/server/lib/server-ipc/utils.ts
 */
export const INTERNAL_HEADERS = [
  MIDDLEWARE_REWRITE_HEADER,
  MIDDLEWARE_REDIRECT_HEADER,
  MIDDLEWARE_SET_COOKIE_HEADER,
  MIDDLEWARE_SKIP_HEADER,
  MIDDLEWARE_OVERRIDE_HEADERS,
  MIDDLEWARE_NEXT_HEADER,
  NOW_ROUTE_MATCHES_HEADER,
  MATCHED_PATH_HEADER,
  NEXTJS_DATA_HEADER,
  NEXT_RESUME_STATE_LENGTH_HEADER,
  ACTION_FORWARDED_HEADER,
];

/** Vinext-only internal headers stripped alongside Next.js protocol internals. */
export const VINEXT_INTERNAL_HEADERS = [
  VINEXT_CACHEABILITY_PROBE_HEADER.toLowerCase(),
  VINEXT_CACHEABILITY_PROBE_ROUTE_HEADER.toLowerCase(),
  VINEXT_EXPECTED_WORKER_VERSION_HEADER.toLowerCase(),
  VINEXT_PRERENDER_ROUTE_PARAMS_HEADER,
  VINEXT_PRERENDER_SPECULATIVE_HEADER,
  VINEXT_PRERENDER_CACHE_LIFE_HEADER,
  VINEXT_REVALIDATE_HOST_HEADER,
  VINEXT_REVALIDATED_CACHE_TAG_HEADER,
  VINEXT_TRACE_ERROR_HEADER.toLowerCase(),
  VINEXT_TRACE_BUFFERED_BODY_HEADER.toLowerCase(),
  VINEXT_TRACE_ROUTE_HEADER.toLowerCase(),
];
